### ISSUE TITLE
Example for pane in docs is out of date

### ISSUE THREAD

**Issue by danieljharvey** [owickstrom/gi-gtk-declarative#34]
Hey! Was just playing around and noticed the `pane` type has changed since the docs were written.

This doesn't work now...

```haskell
paned
  [#wideHandle := True]
  (pane (Resize True) (Shrink True) $ widget Label [#label := "Left"])
  (pane (Resize True) (Shrink True) $ widget Label [#label := "Right"])
```

...but this does:

```haskell
paned
  [#wideHandle := True]
  (pane PaneProperties { resize = True, shrink = True } $ widget Label [#label := "Left"])
  (pane PaneProperties { resize = True, shrink = True } $ widget Label [#label := "Right"])
```

If there is a way to directly submit a PR with the change I'd be happy to, if not I hope this is vaguely helpful.

**Comment by owickstrom** [comment]
Oh, thank you! I should get some sort of build process going for the docs, so they are compiled and checked.

I'm still publishing manually from my computer, so I can make the change and publish. Thank you!

**Comment by owickstrom** [comment]
They were already changed, I had just forgotten to publish. Then I should _at least_ make this part of CI on master branch builds. :smile: 

Live at https://owickstrom.github.io/gi-gtk-declarative/widgets/containers/#paned

Thanks again!

**Comment by danieljharvey** [comment]
Ahh, good stuff!
