### ISSUE TITLE
Widget's internal state is not exposed in the `customSubscribe`

### ISSUE THREAD

**Issue by nbrk** [owickstrom/gi-gtk-declarative#39]
Hi.

I'm constructing the `Tablet`, a complex declarative widget for a strategy game. The map/terrain screen is a `Gtk.Layout` in which the units (`Gtk.EventBox`es) are put, moved or deleted. The idea is to have the declarative widget to generate events when the user clicks/interacts with the units. I want the widget to generate something like `TabletWidgetObjectClicked ObjectId`, so I store and calculate from the Parameters a collection of special data in the declarative widget's internal state (`SomeState`).

What is the recommended way to write the equation for the `customSubscribe` function:
  `customSubscribe :: customData -> widget -> (event -> IO ()) -> IO Subscription`
in which I'm supposed to establish all the individual handlers for the dynamically generated `EventBox`es (tagged with `ObjectId`s) and in some sense to map them to the various custom widget's events?

The problem is that the internal state `SomeState` is not exposed in the `customSubscribe` (the only handle I've got is my toplevel Gtk.Box from which everything descends), but I'm sure I'm missing something.

Thanks in advance.

**Comment by owickstrom** [comment]
You're very much correct. I've been meaning to change custom widget to also pass the customState that is "hidden" within SomeState, so that you don't have to mess with Typeable to get it. It was written in a rush, basically, and I haven't had time to fix it. I'm still not certain how to pass around the old and new arguments.

Anyway, I'm on vacation and can probably take a closer lookook at this next week. I'm glad you're looking at using this library for you project! :)

**Comment by owickstrom** [comment]
If you want to use Typeable in the meantime, you can do something like this: https://github.com/owickstrom/komposition/blob/master/src/Komposition/UserInterface/GtkInterface/ThumbnailPreview.hs

**Comment by nbrk** [comment]
Thank you for your reply. I will look into this. (The Komposition editor is definitely a very nice showcase for the library, btw!)

It would be great to have some well-thought mechanism for multiplexing GTK signals/events within the custom widget (so similar signals from children could result in one constructor of the declarative event). For example, I have populated the `Gtk.Layout` with some `Gtk.EventBox`es. The GTK events/signals I would like to catch include:
- left clicks on the `Gtk.EventBox`es
- right clicks on the `Gtk.EventBox`es
- clicks on the `Gtk.Layout` itself (i.e. a place on the map where no unit is present)
- mouse movements over the Layout
etc.
When I catch any of the GTK events/signals above, I would like to know what exactly has happened and how do I construct (emit) the respecting declarative event from the whole widget.

Weird ideas that come into my mind:
- setup raw callbacks with some constant data on subwidget creation (in `customPatch`). In these callbacks the constant data is pushed in a global mutable stack and the `False` is returned, so the same GTK event gets propagated up to the GTK parent, where we catch it (via `customSubscribe`?), pop the data from the stack and construct the declarative event
- go the opposite way and hack around (in my case) to have many simple declarative widgets (declarative `EventBox`es) instead of one composite. The `Gtk.Layout` actually hosting these boxes could become a special kind of `container` widget (with put and move functionality), where the widgets compose the usual way in the model's `view` declaration

Anyway, thanks for your time. I don't fully understand the crucial internals of your library yet, but I'm more than willing to hack more in my spare time.

**Comment by owickstrom** [comment]
For event handling (before the custom widget stuff is refactored), I'd suggest setting everything up in `customSubscribe` using regular GTK+ callbacks and invoking the `(event -> IO ())` action passed into `customSubscribe` to emit your specific events.

So, you'd use the custom state to hold a record of widget instances, and do the Typeable pattern match boilerplate in `customSubscribe` to get your custom state, such that you can attach signal callbacks.

Does that make sense? Sorry for the custom widget story not being very well thought out yet. I'm going to try find some time to improve it, and document it properly.
