### ISSUE TITLE
Document need for -threaded GHC option

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/gi-gtk-declarative#40]
For app.simple to work, you need the -threaded flag enabled when compiling. See first point in #38.

This should be clearly documented.

**Comment by cblp** [comment]
`run` mya just throw an exception if there are no threads.

https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Concurrent.html#v:rtsSupportsBoundThreads

**Comment by owickstrom** [comment]
@cblp good idea!
