### ISSUE TITLE
How do I start a background process and monitor it in gi-gtk-declarative?

### ISSUE THREAD

**Issue by pmiddend** [owickstrom/gi-gtk-declarative#79]
Hi, I hope questions are fine here. Please tell me where to put them otherwise.

I want to start a long-running process in the background (think about a big background download). I want my declarative UI to display the progress and react to its completion.

With gi-gtk-declarative-app-simple, I can apparently create a background process that triggers *one* event using the `Transition` constructor's second argument. But that doesn't cover my case exactly, because how would I update its progress, say, at regular intervals?

Is the proposed solution to create regular "tick" events using the `inputs` list and check background processes that way?

**Comment by Dretch** [comment]
I have not tested it, but I suppose you could do this without using `inputs` by waiting a while before returning the event from the IO action.

I.e. something like:
```haskell
data Event
  = BackgroundProcessStart
  | BackgroundProcessUpdate Integer 
  | BackgroundProcessFinished
```

When the `update` function handles `BackgroundProcessStart` it would start the background process and the return an IO action that immediately returns `BackgroundProcessUpdate 0`

When the `update` function handles `BackgroundProcessUpdate x` it could wait a while before checking the state of the background process and then either return `BackgroundProcessUpdate (x + 1)` (causing a loop) or `BackgroundProcessFinished` (finishing the loop).

**Comment by pmiddend** [comment]
Okay @Dretch, this actually worked. Thanks!
