### ISSUE TITLE
Dependency version bumps are not released to Hackage.

### ISSUE THREAD

**Issue by kindaro** [owickstrom/gi-gtk-declarative#95]
I think a new Hackage release is needed.

See this line:

https://github.com/owickstrom/gi-gtk-declarative/blob/8fd9c795c19d8e8c1ae1b956fbdae7102efc7a3b/gi-gtk-declarative/gi-gtk-declarative.cabal#L61

On Hackage, [it looks like this](https://hackage.haskell.org/package/gi-gtk-declarative-0.6.3/src/gi-gtk-declarative.cabal):

                      , haskell-gi             >= 0.21 && <0.24

This change is important because of #89 and ultimately haskell-gi/haskell-gi#318, which are all by now fixed.

**Comment by owickstrom** [comment]
Thanks. Both packages are now released as version `0.7.0`.

**Comment by kindaro** [comment]
Thanks, I confirm that it works!
